<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240329162314 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE completed_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, grade SMALLINT NOT NULL, student_id INT DEFAULT NULL, task_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX completed_task__student_id__ind ON completed_task (student_id)');
        $this->addSql('CREATE INDEX completed_task__task_id__ind ON completed_task (task_id)');
        $this->addSql('CREATE TABLE course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE lesson (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(128) NOT NULL, course_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX lesson__course_id__ind ON lesson (course_id)');
        $this->addSql('CREATE TABLE percentage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, percent DOUBLE PRECISION NOT NULL, task_id INT DEFAULT NULL, skill_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX percentage__task_id__ind ON percentage (task_id)');
        $this->addSql('CREATE INDEX percentage__skill_id__ind ON percentage (skill_id)');
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, first_name VARCHAR(64) NOT NULL, last_name VARCHAR(64) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT DEFAULT NULL, course_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX subscription__student_id__ind ON subscription (student_id)');
        $this->addSql('CREATE INDEX subscription__course_id__ind ON subscription (course_id)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(128) NOT NULL, lesson_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX task__lesson_id__ind ON task (lesson_id)');
        $this->addSql('ALTER TABLE completed_task ADD CONSTRAINT completed_task__student_id__fk FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE completed_task ADD CONSTRAINT completed_task__task_id__fk FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT lesson__course_id__fk FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE percentage ADD CONSTRAINT percentage__task_id__fk FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE percentage ADD CONSTRAINT percentage__skill_id__fk FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT subscription__student_id__fk FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT subscription__course_id__fk FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT task__lesson_id__fk FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE completed_task DROP CONSTRAINT completed_task__student_id__fk');
        $this->addSql('ALTER TABLE completed_task DROP CONSTRAINT completed_task__task_id__fk');
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT lesson__course_id__fk');
        $this->addSql('ALTER TABLE percentage DROP CONSTRAINT percentage__task_id__fk');
        $this->addSql('ALTER TABLE percentage DROP CONSTRAINT percentage__skill_id__fk');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT subscription__student_id__fk');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT subscription__course_id__fk');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT task__lesson_id__fk');
        $this->addSql('DROP TABLE completed_task');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE lesson');
        $this->addSql('DROP TABLE percentage');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE task');
    }
}
