###
POST http://127.0.0.1:7777/api/v2/token
Authorization: Basic aS5wZXRyb3Y6MTIzNDU2Nzg=
Content-Type: application/json

{
}

###
PATCH http://127.0.0.1:7777/api/v1/completed-task
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjMwNjEyNDMsImV4cCI6MTcyMzA2NDg0MywiaWQiOjMsImxvZ2luIjoiaS5wZXRyb3YiLCJyb2xlcyI6WyJST0xFX1RFQUNIRVIiXX0.cMtW_ha6sY7Ozuq2p_uXPt9rZC283XGI6UJezi3Y35lAY9AmEDRTgAVv0NNhs3t-5sqz_Y_EnPcUA5w4guImsncf5ryGzlnzSnKrWt3TwuWoD7c6eQfA57kx13AehqshX9CRha1xFQiLcVTzv_ShMOQ-5XC9ZyEkY-vkDs0MLy5UVumaWnH6XT38_LfvnMQvDOLwy-zA78f-SPMVydGWE0kX8wxqCpt0tiybCV2P1aATYuqaOlepfph69Vr1sVM29nkCfjp0DGvfS4Up1QV6clq0NpTmKbvPTsyDhYrhpcskeCCeneuDEiSpEUi08GHyyFRYKpW_H_xx5NDanMCTbnk82YdcCSviYtJnENyTpctcOVYs5B_Zo8_MMMx3yVOOZiZBtaYRZcaSaaZGwk4DBidbUP41Q9qKTEQpiWxd5_LH9vOHUcoBaZ3l9m9UOaxbvcHaUdwMs7DizY0JZR1tMu5Foac6_RftVnR4Lk-tEp1M23Yq_CrMoxL9IT4MAW1NZOBc5Z3MrbbjtEuOS2RtG5cVVIQyLDUhFGg5vUpGCEt4XmMc0v2m7pfuDkbljGZ9XDkNz-Tq1_UfbllwVCheHwdU3v6wroCqYMiKGkQmT4dQwoBzeyWrp-pxDOg_wSI-dOOESVBjb4f-ldJ9AFbKdpTZ7KeAjQEmmS2W1IY7v7w

{
	"id": 26,
	"grade": 5
}

###
GET http://127.0.0.1:7777/api/v1/completed-task?lessonId=2&studentId=3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjMwNjEyNDMsImV4cCI6MTcyMzA2NDg0MywiaWQiOjMsImxvZ2luIjoiaS5wZXRyb3YiLCJyb2xlcyI6WyJST0xFX1RFQUNIRVIiXX0.cMtW_ha6sY7Ozuq2p_uXPt9rZC283XGI6UJezi3Y35lAY9AmEDRTgAVv0NNhs3t-5sqz_Y_EnPcUA5w4guImsncf5ryGzlnzSnKrWt3TwuWoD7c6eQfA57kx13AehqshX9CRha1xFQiLcVTzv_ShMOQ-5XC9ZyEkY-vkDs0MLy5UVumaWnH6XT38_LfvnMQvDOLwy-zA78f-SPMVydGWE0kX8wxqCpt0tiybCV2P1aATYuqaOlepfph69Vr1sVM29nkCfjp0DGvfS4Up1QV6clq0NpTmKbvPTsyDhYrhpcskeCCeneuDEiSpEUi08GHyyFRYKpW_H_xx5NDanMCTbnk82YdcCSviYtJnENyTpctcOVYs5B_Zo8_MMMx3yVOOZiZBtaYRZcaSaaZGwk4DBidbUP41Q9qKTEQpiWxd5_LH9vOHUcoBaZ3l9m9UOaxbvcHaUdwMs7DizY0JZR1tMu5Foac6_RftVnR4Lk-tEp1M23Yq_CrMoxL9IT4MAW1NZOBc5Z3MrbbjtEuOS2RtG5cVVIQyLDUhFGg5vUpGCEt4XmMc0v2m7pfuDkbljGZ9XDkNz-Tq1_UfbllwVCheHwdU3v6wroCqYMiKGkQmT4dQwoBzeyWrp-pxDOg_wSI-dOOESVBjb4f-ldJ9AFbKdpTZ7KeAjQEmmS2W1IY7v7w

###
GET http://127.0.0.1:7777/api/v1/completed-task?skillId=1&studentId=3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjI4ODIwMjUsImV4cCI6MTcyMjg4NTYyNSwiaWQiOjMsImxvZ2luIjoiaS5wZXRyb3YiLCJyb2xlcyI6WyJST0xFX1RFQUNIRVIiXX0.dWTrzclbPGScsOV6mmmrT2GJDeZItd1zfZSUKo1qjoOR_P8QU_wjvZgnFloVI5hZFZlFGzNQcRK4pFX-cZWa04AhBradY1zFoOeoby3mhRtwrJTJD9lQCyWmBy5e3EewlgJyRRtUfrzgYWEq4B9uYfaVwFmzRd8WNh8Z2ViUiUAXBgdm0CG1Wmsk3qFKlKxa_Xxm0YCFFoO_RrQ128_B5_338p9xR7siHNnm_ySic-1jTZMpkaOKOjAd96fUS5kuSECaejAoeU7mb5dtWjOpFV35DvthJ-3c1WABed-RztQ1HpabEmgRE8UxXbo5eTJRpKawXb6_WP7uVh4m3hMTCsvDH8B6pJyocRQa_rXcn34jsk0LjezgnNhjq5e_PKMJuM7all63SObE_T9b1tCuyeL-jdkbz1ciFDQNfEBmveUIdxpmAaR9Ukz8eq_vGVTzG0I0u2EEZp5ms4XwHdbSlniYfLh3g88E4wZuXM3Z28nJ7nNVhasnfs_wMDrDQT79cClkypcmJC5YKhRPNvuZI6fAyU5fQX1ML625hyIvVo895XyByERk0f8WSnGt9xh0tKiHT3p1fqtwfcghzTQ3T4l5ZwMcwns9M_zZnx1XJTC-qrCqrHdtNPcVN3OKTtnOH1-_Z_tULhjEGI8g5s4cFiI_vU9WN0uUyGA7ZymrCFE

###
GET http://127.0.0.1:7777/api/v1/completed-task?page=1&perPage=10
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjMwNTE5MjksImV4cCI6MTcyMzA1NTUyOSwiaWQiOjMsImxvZ2luIjoiaS5wZXRyb3YiLCJyb2xlcyI6WyJST0xFX1RFQUNIRVIiXX0.EBzy-x-pBNIVfAObgc0dABlHBaiBeHtb7kCoCeRSPaMDaAYscsXWiL6H2KBqOqWr-qEDB0XnXx1_9waAxlpLMvTupvGZOHpN4Sm2lVxqXOYCaAqJfx7OhZ-h5be7gBSEqAtGp6o4svs1of-rpJwqPyf9zARDUnWE0FFAnUljzp3N6IvDRY9pRekHt1aApKsbiNAzyRMmqnRFxUidzad4Bts5_GbhMQAfcAvwMfnkYu5SVcosdFeMU7ejoRvmI4p6g4Li8KxVguxfAcIrQbGvoAZBzQ0RPugfLVPHaCZq18x49hApfnGoHKA7FKNtvIScan-IZEruAw5deRjUXXYHiM2ebOxsJY65hU0ficlrxz747ouMz_JoZMOnvBp3Sl_dhqZSrXAKRXjiLP00iv9Rf6PHKsCmKQ2cbH5rFK5up9ARh94VBdSeI1NSgM-bUQeJt_zMGMrIb5JdJZLft1paGuZLLGiurRk3AuuJc_dhkDx4UZnOg4ph8CWNzQ2cPiltJ8rIoHxVj7y0RBA4dAPwh9FSdZsj51diePTM430NdqaebpZQyKpYqtmfdVpo2pPgoAihe84B9m0fhmhonUqupfG5yAqpX_uYShuJiZWZdOJBXMbx_D6zMzamonfuLnMqpzeiNpi_YG9aBQS8UKBuFY8WJYe8I7Ugi3cMX0g60cA
